### ISSUE TITLE
scipy distribution issue

### ISSUE THREAD

**Issue by fbosche** [RudolfCardinal/pdn_project_allocation#11]
I would like to test this package but I get the following error during installation:

> Could not find a version that satisfies the requirement scipy==1.10.1 [...] No matching distribution for scipy==1.10.1

When I try to install `scipy` manually, I get the same error message again.

Could it be that your `setup.py` requires updating? In fact, I wonder if the version constraints in the `install_require` are really necessary.

**Comment by fbosche** [comment]
Just to say that removing all the version constraints seems to have done the trick. I'm now able to run the tool (which seems great, thank you)

**Comment by RudolfCardinal** [comment]
Thanks. What operating system etc. are you running? I've just done a clean install (via ``pip install -e .`` from the project's directory in a clean virtual environment) with Ubuntu 22.04.04, Python 3.10, and that works fine. Running ``pip install scipy==999`` (a non-existent version) lists the versions available:

ERROR: Could not find a version that satisfies the requirement scipy==999 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc1, 1.13.0, 1.13.1, 1.14.0rc1, 1.14.0rc2, 1.14.0)

so 1.10.1 neither the oldest or the newest. Likewise, the versions are available at https://pypi.org/project/scipy/ (e.g. "Release History").

All the best, Rudolf.

**Comment by fbosche** [comment]
I'm on Windows (running from command line of PyCharm).
In any case, why the version constraints? My understanding is that it's generally not a good idea if not strictly necessary.

**Comment by RudolfCardinal** [comment]
General advice is to have liberal version restrictions for libraries (or any other software that has to coexist with unknown other software), so that apps using them have maximum flexibility, but to pin versions exactly for standalone end apps, so things are tested and consistent (usually in the context of a virtual environment); e.g. https://stackoverflow.com/questions/28509481/should-i-pin-my-python-dependencies-versions.

**Comment by fbosche** [comment]
It’s fine; it’s your decision and I understand the motivation (easier on you). But you may at least suggest somewhere that it may well work without those restrictions --- and it in fact did well for me, without having to work out reinstalling the exact versions needed (easier on the users of your solution).

Regardless, your solution works quite nicely. I now firmly intend to apply it full scale in a few weeks. I cross fingers that it will save me a ton of time 😊

**Comment by RudolfCardinal** [comment]
Well, OK, let's give it a go. The intention was to improve ease for users by strengthening the guarantee it would work! But I have extended the version constraints, based on the semantic version promise (https://semver.org/) that the public API won't change until the major version does; thus, in the range ">= tested, < next_major_version".

Good luck with the project allocation!

**Comment by fbosche** [comment]
I think this is a reasonable attempt. Thank you.
